#!/bin/bash
mkdir -p webcam
cd webcam
if ! test -f droidcam_latest.zip; then
  echo "Descargando droidcam."
  wget -O droidcam_latest.zip https://files.dev47apps.net/linux/droidcam_2.1.3.zip
fi
# sha1sum: 2646edd5ad2cfb046c9c695fa6d564d33be0f38b
unzip droidcam_latest.zip -d droidcam
cd droidcam && sudo ./install-clien
echo "Instalando video."
sudo ./install-video
cd ..
if [ -d droidcam ]; then
    echo "eliminado directorio droidcam."
  rm -rf droidcam
fi
echo "Droidcam instalado"
echo "Presione una tecla para salir"
read && kill -9 $PPID



